# Imagen base oficial para Lambda en Python
FROM public.ecr.aws/lambda/python:3.9

# Establecer directorio de trabajo
WORKDIR /var/task

# Copiar requirements e instalar dependencias
COPY src/lambda/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la función Lambda
COPY src/lambda/lambda_volatilidad.py .

# Comando de inicio para Lambda
CMD ["lambda_volatilidad.lambda_handler"]
