FROM python:3.11.5-slim-bullseye

WORKDIR /app

# Copiar todo el módulo src con su jerarquía
COPY src/ ./src/

# Copiar el requirements.txt desde su ubicación real
COPY src/dash/requirements.txt .

# Instalar dependencias
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt


EXPOSE 8050

CMD ["gunicorn", "-b", "0.0.0.0:8050", "src.dash.app_dash:server"]

